# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forum.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Forum(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(598, 599)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 561, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.background_2 = QtWidgets.QLabel(self.frame)
        self.background_2.setGeometry(QtCore.QRect(20, 10, 531, 571))
        self.background_2.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.background_2.setText("")
        self.background_2.setScaledContents(True)
        self.background_2.setObjectName("background_2")
        self.forum_all = QtWidgets.QFrame(self.frame)
        self.forum_all.setGeometry(QtCore.QRect(30, 20, 511, 521))
        self.forum_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.forum_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.forum_all.setObjectName("forum_all")
        self.post_button_frame = QtWidgets.QFrame(self.forum_all)
        self.post_button_frame.setGeometry(QtCore.QRect(10, 419, 491, 91))
        self.post_button_frame.setStyleSheet("")
        self.post_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post_button_frame.setObjectName("post_button_frame")
        self.status = QtWidgets.QPlainTextEdit(self.post_button_frame)
        self.status.setGeometry(QtCore.QRect(20, 10, 461, 31))
        self.status.setTabletTracking(True)
        self.status.setAcceptDrops(False)
        self.status.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(231, 231, 231);\n"
"font: 75 8pt \"Segoe UI\";\n"
"border: 1px solid white;")
        self.status.setObjectName("status")
        self.post_button = QtWidgets.QPushButton(self.post_button_frame)
        self.post_button.setGeometry(QtCore.QRect(30, 45, 441, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.post_button.setFont(font)
        self.post_button.setStyleSheet("border: 1px solid white;\n"
"background-color: rgb(255, 190, 26);\n"
"font: 75 9pt \"Calibri\";")
        self.post_button.setObjectName("post_button")
        self.frame_4 = QtWidgets.QFrame(self.forum_all)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 491, 391))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.post1_frame = QtWidgets.QFrame(self.frame_4)
        self.post1_frame.setGeometry(QtCore.QRect(20, 10, 461, 80))
        self.post1_frame.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.post1_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post1_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post1_frame.setObjectName("post1_frame")
        self.profile_pic = QtWidgets.QLabel(self.post1_frame)
        self.profile_pic.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.profile_pic.setBaseSize(QtCore.QSize(0, 0))
        self.profile_pic.setAutoFillBackground(False)
        self.profile_pic.setStyleSheet("border-radius: 20px;\n"
"border-image: url(:/back/Screenshot_2023-12-30-22-21-52-820_com.instagram.android.jpg);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.profile_pic.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_pic.setFrameShadow(QtWidgets.QFrame.Plain)
        self.profile_pic.setText("")
        self.profile_pic.setScaledContents(True)
        self.profile_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_pic.setWordWrap(False)
        self.profile_pic.setObjectName("profile_pic")
        self.username = QtWidgets.QLabel(self.post1_frame)
        self.username.setGeometry(QtCore.QRect(70, 20, 381, 16))
        self.username.setStyleSheet("font: 75 italic 9pt \"Calibri\";")
        self.username.setObjectName("username")
        self.posting = QtWidgets.QLabel(self.post1_frame)
        self.posting.setGeometry(QtCore.QRect(70, 40, 381, 16))
        self.posting.setObjectName("posting")
        self.post2_frame = QtWidgets.QFrame(self.frame_4)
        self.post2_frame.setGeometry(QtCore.QRect(20, 100, 461, 80))
        self.post2_frame.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.post2_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post2_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post2_frame.setObjectName("post2_frame")
        self.profile_pic_2 = QtWidgets.QLabel(self.post2_frame)
        self.profile_pic_2.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.profile_pic_2.setBaseSize(QtCore.QSize(0, 0))
        self.profile_pic_2.setAutoFillBackground(False)
        self.profile_pic_2.setStyleSheet("border-radius: 20px;\n"
"border-image: url(:/logo/pngegg.png);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.profile_pic_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_pic_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.profile_pic_2.setText("")
        self.profile_pic_2.setScaledContents(True)
        self.profile_pic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_pic_2.setWordWrap(False)
        self.profile_pic_2.setObjectName("profile_pic_2")
        self.username_2 = QtWidgets.QLabel(self.post2_frame)
        self.username_2.setGeometry(QtCore.QRect(70, 20, 381, 16))
        self.username_2.setStyleSheet("font: 75 italic 9pt \"Calibri\";")
        self.username_2.setObjectName("username_2")
        self.posting_2 = QtWidgets.QLabel(self.post2_frame)
        self.posting_2.setGeometry(QtCore.QRect(70, 40, 381, 16))
        self.posting_2.setObjectName("posting_2")
        self.post3_frame = QtWidgets.QFrame(self.frame_4)
        self.post3_frame.setGeometry(QtCore.QRect(20, 190, 461, 80))
        self.post3_frame.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.post3_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post3_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post3_frame.setObjectName("post3_frame")
        self.profile_pic_3 = QtWidgets.QLabel(self.post3_frame)
        self.profile_pic_3.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.profile_pic_3.setBaseSize(QtCore.QSize(0, 0))
        self.profile_pic_3.setAutoFillBackground(False)
        self.profile_pic_3.setStyleSheet("border-radius: 20px;\n"
"border-image: url(:/logo/pngegg.png);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.profile_pic_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_pic_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.profile_pic_3.setText("")
        self.profile_pic_3.setScaledContents(True)
        self.profile_pic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_pic_3.setWordWrap(False)
        self.profile_pic_3.setObjectName("profile_pic_3")
        self.username_3 = QtWidgets.QLabel(self.post3_frame)
        self.username_3.setGeometry(QtCore.QRect(70, 20, 381, 16))
        self.username_3.setStyleSheet("font: 75 italic 9pt \"Calibri\";")
        self.username_3.setObjectName("username_3")
        self.posting_3 = QtWidgets.QLabel(self.post3_frame)
        self.posting_3.setGeometry(QtCore.QRect(70, 40, 381, 16))
        self.posting_3.setObjectName("posting_3")
        self.post4_frame = QtWidgets.QFrame(self.frame_4)
        self.post4_frame.setGeometry(QtCore.QRect(20, 280, 461, 80))
        self.post4_frame.setStyleSheet("background-color: rgb(248, 248, 248);")
        self.post4_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.post4_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.post4_frame.setObjectName("post4_frame")
        self.profile_pic_4 = QtWidgets.QLabel(self.post4_frame)
        self.profile_pic_4.setGeometry(QtCore.QRect(10, 20, 41, 41))
        self.profile_pic_4.setBaseSize(QtCore.QSize(0, 0))
        self.profile_pic_4.setAutoFillBackground(False)
        self.profile_pic_4.setStyleSheet("border-radius: 20px;\n"
"border-image: url(:/logo/pngegg.png);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.profile_pic_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.profile_pic_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.profile_pic_4.setText("")
        self.profile_pic_4.setScaledContents(True)
        self.profile_pic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_pic_4.setWordWrap(False)
        self.profile_pic_4.setObjectName("profile_pic_4")
        self.username_4 = QtWidgets.QLabel(self.post4_frame)
        self.username_4.setGeometry(QtCore.QRect(70, 20, 381, 16))
        self.username_4.setStyleSheet("font: 75 italic 9pt \"Calibri\";")
        self.username_4.setObjectName("username_4")
        self.posting_4 = QtWidgets.QLabel(self.post4_frame)
        self.posting_4.setGeometry(QtCore.QRect(70, 40, 381, 16))
        self.posting_4.setObjectName("posting_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.status.setPlainText(_translate("Dialog", "What\'s on your mind today?"))
        self.post_button.setText(_translate("Dialog", "Post"))
        self.username.setText(_translate("Dialog", "Lejosette"))
        self.posting.setText(_translate("Dialog", "I feel so alive todayyyyy!!!!!"))
        self.username_2.setText(_translate("Dialog", "username 2"))
        self.posting_2.setText(_translate("Dialog", "posting ....."))
        self.username_3.setText(_translate("Dialog", "username 3"))
        self.posting_3.setText(_translate("Dialog", "posting ....."))
        self.username_4.setText(_translate("Dialog", "username 4"))
        self.posting_4.setText(_translate("Dialog", "posting ....."))


import background
import logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_Forum()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
