# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Home(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(597, 598)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 20, 561, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.background = QtWidgets.QLabel(self.frame)
        self.background.setGeometry(QtCore.QRect(0, 0, 561, 561))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.background.setFont(font)
        self.background.setStyleSheet("border-image: url(:/back/7440.jpg);")
        self.background.setObjectName("background")
        self.fade = QtWidgets.QLabel(self.frame)
        self.fade.setGeometry(QtCore.QRect(-10, -10, 591, 591))
        self.fade.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"")
        self.fade.setText("")
        self.fade.setObjectName("fade")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 60, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(30, 30, 71, 71))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.desc = QtWidgets.QLabel(self.frame)
        self.desc.setGeometry(QtCore.QRect(80, 190, 431, 121))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.desc.setFont(font)
        self.desc.setStyleSheet("color: rgb(255, 255, 255);")
        self.desc.setObjectName("desc")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(80, 350, 91, 21))
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 350, 91, 21))
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 350, 91, 21))
        self.pushButton_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(140, 470, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.background.setText(_translate("Dialog", "l"))
        self.label.setText(_translate("Dialog", "MEDICAL DIAGNOSTICIAN"))
        self.desc.setText(_translate("Dialog", "Artificial Neural Networks in healthcare websites and\n"
" apps revolutionize medical analysis, diagnosis, and\n"
" treatment by leveraging advanced technology to\n"
" enhance doctors\' capabilities and provide more\n"
" accurate and efficient care globally."))
        self.pushButton.setText(_translate("Dialog", "Diagnose"))
        self.pushButton_2.setText(_translate("Dialog", "Forum"))
        self.pushButton_3.setText(_translate("Dialog", "Profile"))
        self.label_2.setText(_translate("Dialog", "\"Prevention is better than cure\""))

import background
import logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_Home()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
