# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 20, 561, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.background = QtWidgets.QLabel(self.frame)
        self.background.setGeometry(QtCore.QRect(20, 10, 531, 571))
        self.background.setStyleSheet("image: url(:/back/abstract-grunge-decorative-relief-navy-blue-stucco-wall-texture-wide-angle-rough-colored-background.jpg);\n"
"border-radius: 20px;")
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/back/abstract-grunge-decorative-relief-navy-blue-stucco-wall-texture-wide-angle-rough-colored-background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.shade = QtWidgets.QLabel(self.frame)
        self.shade.setGeometry(QtCore.QRect(30, 20, 511, 511))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.shade.setFont(font)
        self.shade.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"border-radius: 20px;")
        self.shade.setText("")
        self.shade.setObjectName("shade")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(230, 110, 111, 111))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.title = QtWidgets.QLabel(self.frame)
        self.title.setGeometry(QtCore.QRect(160, 50, 271, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 255, 255);")
        self.title.setObjectName("title")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(90, 220, 411, 41))
        self.label.setStyleSheet("font: 10pt \"Segoe Print\";\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.frame)
        self.password.setGeometry(QtCore.QRect(230, 310, 113, 20))
        self.password.setStyleSheet("border-radius: 5px;")
        self.password.setText("")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.login = QtWidgets.QPushButton(self.frame)
        self.login.setGeometry(QtCore.QRect(250, 340, 75, 23))
        self.login.setStyleSheet("")
        self.login.setObjectName("login")
        self.signup = QtWidgets.QPushButton(self.frame)
        self.signup.setGeometry(QtCore.QRect(250, 440, 75, 23))
        self.signup.setObjectName("signup")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(230, 420, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(230, 280, 113, 20))
        self.email.setStyleSheet("border-radius: 5px;")
        self.email.setText("")
        self.email.setAlignment(QtCore.Qt.AlignCenter)
        self.email.setObjectName("email")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "MEDICAL DIAGNOSTICIAN"))
        self.label.setText(_translate("MainWindow", "\"Revolutionize healthcare with our app\'s cutting-edge ANN\""))
        self.password.setPlaceholderText(_translate("MainWindow", "password"))
        self.login.setText(_translate("MainWindow", "Log In"))
        self.signup.setText(_translate("MainWindow", "Sign Up"))
        self.label_2.setText(_translate("MainWindow", "Do not have account?"))
        self.email.setPlaceholderText(_translate("MainWindow", "email"))


import background
import logo


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
